### ISSUE TITLE
How to draw images?

### ISSUE THREAD

**Issue by CuteTenshii** [Core-2-Extreme/GUI_template#2]
in the title

**Comment by Core-2-Extreme** [comment]
Sorry for late reply.
I made an example.
[sub_app0.zip](https://github.com/Core-2-Extreme/GUI_template/files/8451886/sub_app0.zip)
Declare image variable at line 10
Initialize texture and load picture at line 76~92
Draw texture at 265
Free texture at line 114
You need to have `test.png` on your SD card

Hope it helps.

**Comment by CuteTenshii** [comment]
Hello sorry for late reply, I had moved on and forgot about this issue. Thanks for the reply by the way

tomorrow I will take over the dev of the app I was making to put the images I wanted to put

I would also like to know how I could do to display images from the internet (with a url)? does it work the same?

**Comment by Core-2-Extreme** [comment]
It works similar.
I added sample code.
[Loading picture code](https://github.com/Core-2-Extreme/GUI_template/blob/main/source/sub_app0.cpp#L64)
[Displaying picture code](https://github.com/Core-2-Extreme/GUI_template/blob/main/source/sub_app0.cpp#L314)

(This image is used in sample code)
![sample_png](https://user-images.githubusercontent.com/45873899/167138864-b6a9e25e-2dce-49d0-9b5a-d5986e768ad6.png)
